---
bootstrap:
  ignHttpLocation: http://192.168.86.180:8080/ignition/bootstrap.ign 
config:
  baseDomain: example.com
  clusterName: ocp4
  sshKey: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pullSecret: {"auths": ... }
vcenter:
  ip: 192.168.86.100
  datastore: datastore1
  network: VM Network
  service_account_username: administrator@vsphere.local
  service_account_password: something
  admin_username: administrator@vsphere.local 
  admin_password: something 
  datacenter: dc
  vm_power_state: poweredon
  templateName: rhcos-4.3.0-x86_64-vmware
download:
  openshiftClient: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.3.5.tar.gz"
  openshiftInstall: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.3.5.tar.gz"
  govc: "https://github.com/vmware/govmomi/releases/download/v0.22.1/govc_linux_amd64.gz"
  ova: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest/rhcos-4.3.0-x86_64-vmware.ova"
  initramfs: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/latest/rhcos-4.3.0-x86_64-installer-initramfs.img"
  kernel: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/latest/rhcos-4.3.0-x86_64-installer-kernel"
  iso: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/latest/rhcos-4.3.0-x86_64-installer.iso"  
  raw: "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.3/latest/rhcos-4.3.0-x86_64-metal.raw.gz"
