helper_vm_ip: 192.168.86.180
bootstrap_ignition_url: "http://{{helper_vm_ip}}:8080/ignition/bootstrap.ign"  
config:
  provider: vsphere
  base_domain: example.com
  cluster_name: ocp4
  installer_ssh_key: "{{ lookup('file', '~/.ssh/ocp4.pub') }}"
  pull_secret: {"auths": ...}
vcenter:
  ip: 192.168.86.100
  datastore: datastore1
  network: VM Network
  service_account_username: administrator@vsphere.local
  service_account_password: something
  admin_username: administrator@vsphere.local 
  admin_password: something
  datacenter: dc
  vm_power_state: poweredon
  templateName: rhcos-vmware
download:
  clients_url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest
  dependencies_url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/latest/latest
  govc: https://github.com/vmware/govmomi/releases/download/v0.22.1/govc_linux_amd64.gz
bootstrap_vms: 
  - { name: "bootstrap", macaddr: "00:50:56:a8:aa:a1", ipaddr: "192.168.86.181"}
master_vms:
  - { name: "master0", macaddr: "00:50:56:a8:aa:a2", ipaddr: "192.168.86.182"}
  - { name: "master1", macaddr: "00:50:56:a8:aa:a3", ipaddr: "192.168.86.183"}
  - { name: "master2", macaddr: "00:50:56:a8:aa:a4", ipaddr: "192.168.86.184"}
worker_vms:      
  - { name: "worker0", macaddr: "00:50:56:a8:aa:a5", ipaddr: "192.168.86.185"}
  - { name: "worker1", macaddr: "00:50:56:a8:aa:a6", ipaddr: "192.168.86.186"}
  - { name: "worker2", macaddr: "00:50:56:a8:aa:a7", ipaddr: "192.168.86.187"} 
static_ip:
  gateway: 192.168.86.1
  netmask: 255.255.255.0
  network_interface_name: ens192
proxy:
  enabled: true
  http_proxy: http://helper.ocp4.example.com:3129
  https_proxy: http://helper.ocp4.example.com:3129
  no_proxy: example.com
  cert_content: |
    -----BEGIN CERTIFICATE-----
        <certficate content>
    -----END CERTIFICATE-----  
registry:
  enabled: true
  product_repo: openshift-release-dev
  product_release_name: ocp-release
  product_release_version: 4.4.0-x86_64
  username: ansible
  password: ansible
  email: user@awesome.org
  cert_content:
  host: registry.ocp4.example.com
  port: 5000
  repo: ocp4/openshift4
