- name: Create bootstrap VM from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}"
    state: poweredoff
    template: "{{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }}"
    disk:
    - size_gb: 120
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    wait_for_ip_address: no
    advanced_settings:
      - key: guestinfo.ignition.config.data
        value: "{{ bootstrapContent }}"
      - key: guestinfo.ignition.config.data.encoding
        value: base64
  loop: "{{ bootstrap_vms }}"

- name: Configure network for bootstrap VM
  vmware_guest_network:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    name: "{{ item.name }}"
    network_name: "{{ vcenter.network }}"
    mac_address: "{{ item.macaddr | default(omit) }}"
  loop: "{{ bootstrap_vms }}"

- name: Power on bootstrap VM
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}"
    state: poweredon
  loop: "{{ bootstrap_vms }}"

- name: Create control plane VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}"
    state: poweredoff
    template: "{{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }}"
    disk:
    - size_gb: 120
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    wait_for_ip_address: no
    advanced_settings:
     - key: guestinfo.ignition.config.data
       value: "{{ masterContent }}"
     - key: guestinfo.ignition.config.data.encoding
       value: base64
  loop: "{{ master_vms }}"

- name: Configure network for control plane VMs
  vmware_guest_network:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    name: "{{ item.name }}"
    network_name: "{{ vcenter.network }}"
    mac_address: "{{ item.macaddr | default(omit) }}"
  loop: "{{ master_vms }}"

- name: Power on control plane VMs
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}"
    state: poweredon
  loop: "{{ master_vms }}"

- name: Create worker VMs from the template
  vmware_guest:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    folder: "{{ vcenter.folder_absolute_path }}"
    name: "{{ item.name }}"
    state: poweredoff
    template: "{{ vcenter.folder_absolute_path }}/{{ vcenter.template_name }}"
    disk:
    - size_gb: 120
      type: thin
      datastore: "{{ vcenter.datastore }}"
    hardware:
      memory_mb: "{{ item.ram }}"
      num_cpus: "{{ item.cpu }}"
      memory_reservation_lock: True
      version: "{{ vcenter.hw_version }}"
    wait_for_ip_address: no
    advanced_settings:
     - key: guestinfo.ignition.config.data
       value: "{{ workerContent }}"
     - key: guestinfo.ignition.config.data.encoding
       value: base64
  loop: "{{ worker_vms }}"

- name: Configure network for worker VMs
  vmware_guest_network:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.service_account_username }}"
    password: "{{ vcenter.service_account_password }}"
    datacenter: "{{ vcenter.datacenter }}"
    validate_certs: no
    name: "{{ item.name }}"
    network_name: "{{ vcenter.network }}"
    mac_address: "{{ item.macaddr | default(omit) }}"
  loop: "{{ worker_vms }}"
